name: build-linux-x64

# This file is never triggered directly by a person. The release orchestrator
# You have to add it into the main release.yml because github is too good to allow workflow discovery.
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

permissions:
  id-token: write
  contents: read
  attestations: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.0.x'

      # No cross-compilation toolchain needed here - ubuntu-latest runners
      # are already linux-x64, so this is a native (non-cross) AOT publish.
      - name: Restore
        run: dotnet restore

      - name: Publish AOT (linux-x64)
        run: >
          dotnet publish
          -c Release
          -r linux-x64
          -p:Version=${{ inputs.version }}
          -p:PublishAot=true
          -p:StripSymbols=true
          -p:DebuggerSupport=false
          -p:StackTraceSupport=false
          -p:InvariantGlobalization=true
          -p:IlcUseLLVM=true
          -p:IlcInstructionSet=x86-64-v2
          --self-contained true
          -o ./publish
          
      - name: Generate artifact attestation
        uses: actions/attest@v4
        with:
          subject-path: publish/Prx.Camera

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: prx-camera-linux-x64-${{ inputs.version }}
          path: publish/Prx.Camera
          if-no-files-found: error
